### ISSUE TITLE
extractPostag.sh not generating the sample file

### ISSUE THREAD

**Issue by Saumajit** [cs329yangzhong/specificityTwitter#1]
Blank file is created. Can you please suggest what can be the possible reason? There is an error _Length of values does not match length of index_ because length of big_matrix is 0.

**Comment by cs329yangzhong** [comment]
Hi Saumajit, Did you set up the tagger following the prompt in the READ file and the official tutorial of the Tagger? For your convenience, I have also updated the readme with the [link](https://drive.google.com/file/d/18CZ07XpE-JkWpoHNf5NIdNaO0O70S86F/view) to the exact same tagger we used. I tested it on my laptop and it works fine. 

Also please make sure your input format is correct -- each line with one tweet.  Feel free to let me know if you still have difficulties.

**Comment by cs329yangzhong** [comment]
> Hi Saumajit, Did you set up the tagger following the prompt in the READ file and the official tutorial of the Tagger? For your convenience, I have also updated the readme with the [link](https://drive.google.com/file/d/18CZ07XpE-JkWpoHNf5NIdNaO0O70S86F/view) to the exact same tagger we used. I tested it on my laptop and it works fine.
> 
> Also please make sure your input format is correct -- each line with one tweet. Feel free to let me know if you still have difficulties.

Hi Saumajit, has the problem been solved? If so, I will close this issue soon.
